import json from '@a2zb/packages/abis/dmrkt/OrderEngine.json' with { type: 'json' }

import { toFunctionSelector, recoverPublicKey, decodeFunctionData, Abi, AbiFunction } from 'viem'

import { publicClient as client } from '#app/client.js'
import { Hex } from '#app/utils/format/hex.js'

import { TxContext } from './types/context.js'

const RPC_URL = process.env.RPC_URL

//export const txMeta = async <T>(txHash: Hex32, normalize: () => T) => {

export const txMeta = async (txHash: Hex) => {
  const tx = await client.getTransaction({ hash: txHash })
  const receipt = await client.getTransactionReceipt({ hash: txHash })

  const abi = json.abi as Abi

  const abiFunctionMatch = abi.find(
    (x): x is AbiFunction =>
      x.type === 'function' && toFunctionSelector(x) === (tx.input.slice(0, 10) as `0x${string}`)
  )

  if (!abiFunctionMatch) {
    throw new Error('No ABI function match for tx function selector')
  }

  if (!tx.to) {
    throw new Error('Unexpected contract creation tx')
  }

  const txCtx: TxContext = {
    index: tx.transactionIndex,
    gasUsed: receipt.gasUsed.toString(),
    effectiveGasPrice: receipt.effectiveGasPrice.toString(),
    functionSelector: tx.input.slice(0, 10) as `0x${string}`,
    functionName: abiFunctionMatch.name,
    contractAddress: tx.to,
  }

  // tmp settlement logic specific => later todo: pass normalize function to generalize
  //const { functionName } = decodeFunctionData({ abi: json.abi, data: tx.input })
  // const meta: SettlementMeta = {
  //  side: ;
  //  gasUsed: receipt.gasUsed;
  //  effectiveGasPrice:
  //
  // }

  // const tx: {
  //     nonce: number;
  //     v: bigint;
  //     r: `0x${string}`;
  //     s: `0x${string}`;
  //     type: "legacy";
  //     yParity?: undefined;
  //     from: `0x${string}`;
  //     gas: bigint;
  //     hash: `0x${string}`;
  //     input: `0x${string}`;
  //     to: `0x${string}` | null;
  //     typeHex: `0x${string}` | null;
  //     value: bigint;
  //     accessList?: undefined;
  //     authorizationList?: undefined;
  //     blobVersionedHashes?: undefined;
  //     chainId?: number | undefined;
  //     gasPrice: bigint;
  //     maxFeePerBlobGas?: undefined;
  //     maxFeePerGas?: undefined;
  //     maxPriorityFeePerGas?: undefined;
  //     blockHash: `0x${string}`;
  //     blockNumber: bigint;
  //     transactionIndex: number;
  // }

  //  const receipt: {
  //     blobGasPrice?: bigint | undefined;
  //     blobGasUsed?: bigint | undefined;
  //     blockHash: `0x${string}`;
  //     blockNumber: bigint;
  //     contractAddress: `0x${string}` | null | undefined;
  //     cumulativeGasUsed: bigint;
  //     effectiveGasPrice: bigint;
  //     from: `0x${string}`;
  //     gasUsed: bigint;
  //     logs: Log<bigint, number, false>[];
  //     logsBloom: Hex;
  //     root?: Hash | undefined;
  //     status: "success" | "reverted";
  //     to: Address | null;
  //     transactionHash: Hash;
  //     transactionIndex: number;
  //     type: TransactionType;
  // }
}

// export type TransactionReceipt<
//   quantity = bigint,
//   index = number,
//   status = 'success' | 'reverted',
//   type = TransactionType,
// > = {
//   /** The actual value per gas deducted from the sender's account for blob gas. Only specified for blob transactions as defined by EIP-4844. */
//   blobGasPrice?: quantity | undefined
//   /** The amount of blob gas used. Only specified for blob transactions as defined by EIP-4844. */
//   blobGasUsed?: quantity | undefined
//   /** Hash of block containing this transaction */
//   blockHash: Hash
//   /** Number of block containing this transaction */
//   blockNumber: quantity
//   /** Address of new contract or `null` if no contract was created */
//   contractAddress: Address | null | undefined
//   /** Gas used by this and all preceding transactions in this block */
//   cumulativeGasUsed: quantity
//   /** Pre-London, it is equal to the transaction's gasPrice. Post-London, it is equal to the actual gas price paid for inclusion. */
//   effectiveGasPrice: quantity
//   /** Transaction sender */
//   from: Address
//   /** Gas used by this transaction */
//   gasUsed: quantity
//   /** List of log objects generated by this transaction */
//   logs: Log<quantity, index, false>[]
//   /** Logs bloom filter */
//   logsBloom: Hex
//   /** The post-transaction state root. Only specified for transactions included before the Byzantium upgrade. */
//   root?: Hash | undefined
//   /** `success` if this transaction was successful or `reverted` if it failed */
//   status: status
//   /** Transaction recipient or `null` if deploying a contract */
//   to: Address | null
//   /** Hash of this transaction */
//   transactionHash: Hash
//   /** Index of this transaction in the block */
//   transactionIndex: index
//   /** Transaction type */
//   type: type
// }
