import oeAbi from '@a2zb/packages/abis/dmrkt/OrderEngine.json' with { type: 'json' }

import { toFunctionSelector, recoverPublicKey } from 'viem'

import { publicClient as client } from '#app/client.js'

import { SettlementMeta } from '#app/domain/types/settlement.js'
import { Hex32 } from '#app/utils/format/hex32.js'

const RPC_URL = process.env.RPC_URL

//export const txMeta = async <T>(txHash: Hex32, normalize: () => T) => {

export const txMeta = async (txHash: Hex32) => {
  const tx = await client.getTransaction({ hash: txHash })
  const receipt = await client.getTransactionReceipt({ hash: txHash })

  // tmp settlement logic specific => later todo: pass normalize function to generalize

  // const meta: SettlementMeta = {
  //   side:
  // }

  //  const receipt: {
  //     blobGasPrice?: bigint | undefined;
  //     blobGasUsed?: bigint | undefined;
  //     blockHash: `0x${string}`;
  //     blockNumber: bigint;
  //     contractAddress: `0x${string}` | null | undefined;
  //     cumulativeGasUsed: bigint;
  //     effectiveGasPrice: bigint;
  //     from: `0x${string}`;
  //     gasUsed: bigint;
  //     logs: Log<bigint, number, false>[];
  //     logsBloom: Hex;
  //     root?: Hash | undefined;
  //     status: "success" | "reverted";
  //     to: Address | null;
  //     transactionHash: Hash;
  //     transactionIndex: number;
  //     type: TransactionType;
  // }
}

// export type TransactionReceipt<
//   quantity = bigint,
//   index = number,
//   status = 'success' | 'reverted',
//   type = TransactionType,
// > = {
//   /** The actual value per gas deducted from the sender's account for blob gas. Only specified for blob transactions as defined by EIP-4844. */
//   blobGasPrice?: quantity | undefined
//   /** The amount of blob gas used. Only specified for blob transactions as defined by EIP-4844. */
//   blobGasUsed?: quantity | undefined
//   /** Hash of block containing this transaction */
//   blockHash: Hash
//   /** Number of block containing this transaction */
//   blockNumber: quantity
//   /** Address of new contract or `null` if no contract was created */
//   contractAddress: Address | null | undefined
//   /** Gas used by this and all preceding transactions in this block */
//   cumulativeGasUsed: quantity
//   /** Pre-London, it is equal to the transaction's gasPrice. Post-London, it is equal to the actual gas price paid for inclusion. */
//   effectiveGasPrice: quantity
//   /** Transaction sender */
//   from: Address
//   /** Gas used by this transaction */
//   gasUsed: quantity
//   /** List of log objects generated by this transaction */
//   logs: Log<quantity, index, false>[]
//   /** Logs bloom filter */
//   logsBloom: Hex
//   /** The post-transaction state root. Only specified for transactions included before the Byzantium upgrade. */
//   root?: Hash | undefined
//   /** `success` if this transaction was successful or `reverted` if it failed */
//   status: status
//   /** Transaction recipient or `null` if deploying a contract */
//   to: Address | null
//   /** Hash of this transaction */
//   transactionHash: Hash
//   /** Index of this transaction in the block */
//   transactionIndex: index
//   /** Transaction type */
//   type: type
// }
